import { PrismaClient } from '../lib/generated/prisma';
import { PrismaPg } from '@prisma/adapter-pg';
import bcrypt from 'bcryptjs';

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log('Seeding database...');

  // Delete in correct order (respecting foreign keys)
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.userAddress.deleteMany();
  await prisma.user.deleteMany();
  await prisma.card.deleteMany();
  await prisma.article.deleteMany();

  console.log('Cleared existing data.');

  // ─── Cards ───────────────────────────────────────────────────────────
  const cardsData = [
    // Anniversary (IDs 1-14)
    {
      id: '1',
      title: 'A Matcha made in heaven',
      description: 'Celebrate love and togetherness with this beautifully designed anniversary card.',
      category: 'anniversary',
      price: 4.99,
      images: { front: '/cards/anniversary/a-matcha-made-in-heaven.png', back: '/cards/anniversary/a-matcha-made-in-heaven-2d.png', thumbnail: '/cards/anniversary/a-matcha-made-in-heaven.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Anniversary', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '2',
      title: 'A dinner out',
      description: 'Celebrate love and togetherness with this beautifully designed anniversary card.',
      category: 'anniversary',
      price: 4.99,
      images: { front: '/cards/anniversary/a-dinner-out.png', back: '/cards/anniversary/a-dinner-out-2d.png', thumbnail: '/cards/anniversary/a-dinner-out.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Anniversary', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '3',
      title: 'Cheers to you',
      description: 'Celebrate love and togetherness with this beautifully designed anniversary card.',
      category: 'anniversary',
      price: 4.99,
      images: { front: '/cards/anniversary/cheers-to-you.png', back: '/cards/anniversary/cheers-to-you-2d.png', thumbnail: '/cards/anniversary/cheers-to-you.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Anniversary', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '4',
      title: 'Flower Hearts',
      description: 'Celebrate love and togetherness with this beautifully designed anniversary card.',
      category: 'anniversary',
      price: 4.99,
      images: { front: '/cards/anniversary/flower-hearts.png', back: '/cards/anniversary/flower-hearts-2d.png', thumbnail: '/cards/anniversary/flower-hearts.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Anniversary', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '5',
      title: 'Hearts',
      description: 'Celebrate love and togetherness with this beautifully designed anniversary card.',
      category: 'anniversary',
      price: 4.99,
      images: { front: '/cards/anniversary/hearts.png', back: '/cards/anniversary/hearts-2d.png', thumbnail: '/cards/anniversary/hearts.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Anniversary', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '6',
      title: 'Jukebox',
      description: 'Celebrate love and togetherness with this beautifully designed anniversary card.',
      category: 'anniversary',
      price: 4.99,
      images: { front: '/cards/anniversary/jukebox.png', back: '/cards/anniversary/jukebox-2d.png', thumbnail: '/cards/anniversary/jukebox.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Anniversary', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '7',
      title: 'Kiss Kiss',
      description: 'Celebrate love and togetherness with this beautifully designed anniversary card.',
      category: 'anniversary',
      price: 4.99,
      images: { front: '/cards/anniversary/kiss-kiss.png', back: '/cards/anniversary/kiss-kiss-2d.png', thumbnail: '/cards/anniversary/kiss-kiss.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Anniversary', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '8',
      title: 'Knockout',
      description: 'Celebrate love and togetherness with this beautifully designed anniversary card.',
      category: 'anniversary',
      price: 4.99,
      images: { front: '/cards/anniversary/knockout.png', back: '/cards/anniversary/knockout-2d.png', thumbnail: '/cards/anniversary/knockout.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Anniversary', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '9',
      title: 'Love you daisy',
      description: 'Celebrate love and togetherness with this beautifully designed anniversary card.',
      category: 'anniversary',
      price: 4.99,
      images: { front: '/cards/anniversary/love-you-daisy.png', back: '/cards/anniversary/love-you-daisy-2d.png', thumbnail: '/cards/anniversary/love-you-daisy.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Anniversary', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '10',
      title: 'Lucky You',
      description: 'Celebrate love and togetherness with this beautifully designed anniversary card.',
      category: 'anniversary',
      price: 4.99,
      images: { front: '/cards/anniversary/lucky-you.png', back: '/cards/anniversary/lucky-you-2d.png', thumbnail: '/cards/anniversary/lucky-you.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Anniversary', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '11',
      title: 'Romantic Songs',
      description: 'Celebrate love and togetherness with this beautifully designed anniversary card.',
      category: 'anniversary',
      price: 4.99,
      images: { front: '/cards/anniversary/romantic-songs.png', back: '/cards/anniversary/romantic-songs-2d.png', thumbnail: '/cards/anniversary/romantic-songs.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Anniversary', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '12',
      title: 'Still holding',
      description: 'Celebrate love and togetherness with this beautifully designed anniversary card.',
      category: 'anniversary',
      price: 4.99,
      images: { front: '/cards/anniversary/still-holding.png', back: '/cards/anniversary/still-holding-2d.png', thumbnail: '/cards/anniversary/still-holding.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Anniversary', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '13',
      title: 'XO',
      description: 'Celebrate love and togetherness with this beautifully designed anniversary card.',
      category: 'anniversary',
      price: 4.99,
      images: { front: '/cards/anniversary/xo.png', back: '/cards/anniversary/xo-2d.png', thumbnail: '/cards/anniversary/xo.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Anniversary', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '14',
      title: "You're still the one",
      description: 'Celebrate love and togetherness with this beautifully designed anniversary card.',
      category: 'anniversary',
      price: 4.99,
      images: { front: '/cards/anniversary/youre-still-the-one.png', back: '/cards/anniversary/youre-still-the-one-2d.png', thumbnail: '/cards/anniversary/youre-still-the-one.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Anniversary', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    // Birthday (IDs 15-48)
    {
      id: '15',
      title: 'All the wheels',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/all-the-wheels.png', back: '/cards/birthday/all-the-wheels-2d.png', thumbnail: '/cards/birthday/all-the-wheels.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '16',
      title: 'Aztec Print',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/aztec-print.png', back: '/cards/birthday/aztec-print-2d.png', thumbnail: '/cards/birthday/aztec-print.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '17',
      title: 'Ballerina',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/ballerina.png', back: '/cards/birthday/ballerina-2d.png', thumbnail: '/cards/birthday/ballerina.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '18',
      title: 'Birthday Princess',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/birthday-princess.png', back: '/cards/birthday/birthday-princess-2d.png', thumbnail: '/cards/birthday/birthday-princess.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '19',
      title: 'Campavan Adventures',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/campavan-adventures.png', back: '/cards/birthday/campavan-adventures-2d.png', thumbnail: '/cards/birthday/campavan-adventures.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '20',
      title: 'Cartoon Fun',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/cartoon-fun.png', back: '/cards/birthday/cartoon-fun-2d.png', thumbnail: '/cards/birthday/cartoon-fun.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '21',
      title: 'Celebration Daddy',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/celebration-daddy.png', back: '/cards/birthday/celebration-daddy-2d.png', thumbnail: '/cards/birthday/celebration-daddy.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '22',
      title: 'Countryside',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/countryside.png', back: '/cards/birthday/countryside-2d.png', thumbnail: '/cards/birthday/countryside.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '23',
      title: 'Cowboy saloon',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/cowboy-saloon.png', back: '/cards/birthday/cowboy-saloon-2d.png', thumbnail: '/cards/birthday/cowboy-saloon.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '24',
      title: 'Crepes and Coffee',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/crepes-and-coffee.png', back: '/cards/birthday/crepes-and-coffee-2d.png', thumbnail: '/cards/birthday/crepes-and-coffee.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '25',
      title: 'Dance All Night',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/dance-all-night.png', back: '/cards/birthday/dance-all-night-2d.png', thumbnail: '/cards/birthday/dance-all-night.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '26',
      title: 'Dried Flowers',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/dried-flowers.png', back: '/cards/birthday/dried-flowers-2d.png', thumbnail: '/cards/birthday/dried-flowers.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '27',
      title: 'Eat, Sleep, Padel, Repeat',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/eat-sleep-padel-repeat.png', back: '/cards/birthday/eat-sleep-padel-repeat-2d.png', thumbnail: '/cards/birthday/eat-sleep-padel-repeat.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '28',
      title: 'Football theme',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/football-theme.png', back: '/cards/birthday/football-theme-2d.png', thumbnail: '/cards/birthday/football-theme.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '29',
      title: 'Geometric',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/geometric.png', back: '/cards/birthday/geometric-2d.png', thumbnail: '/cards/birthday/geometric.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '30',
      title: 'Heart of flowers',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/heart-of-flowers.png', back: '/cards/birthday/heart-of-flowers-2d.png', thumbnail: '/cards/birthday/heart-of-flowers.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '31',
      title: 'Japanese Blossom',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/japanese-blossom.png', back: '/cards/birthday/japanese-blossom-2d.png', thumbnail: '/cards/birthday/japanese-blossom.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '32',
      title: 'Kids Crayons',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/kids-crayons.png', back: '/cards/birthday/kids-crayons-2d.png', thumbnail: '/cards/birthday/kids-crayons.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '33',
      title: 'Kids Drawing Board',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/kids-drawing-board.png', back: '/cards/birthday/kids-drawing-board-2d.png', thumbnail: '/cards/birthday/kids-drawing-board.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '34',
      title: 'Lavender',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/lavender.png', back: '/cards/birthday/lavender-2d.png', thumbnail: '/cards/birthday/lavender.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '35',
      title: 'Like a fine wine',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/like-a-fine-wine.png', back: '/cards/birthday/like-a-fine-wine-2d.png', thumbnail: '/cards/birthday/like-a-fine-wine.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '36',
      title: 'Love you Daddy',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/love-you-daddy.png', back: '/cards/birthday/love-you-daddy-2d.png', thumbnail: '/cards/birthday/love-you-daddy.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '37',
      title: 'Love you Mummy',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/love-you-mummy.png', back: '/cards/birthday/love-you-mummy-2d.png', thumbnail: '/cards/birthday/love-you-mummy.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '38',
      title: 'Many Many',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/many-many.png', back: '/cards/birthday/many-many-2d.png', thumbnail: '/cards/birthday/many-many.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '39',
      title: 'Many Many Many Birthdays',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/many-many-many-birthdays.png', back: '/cards/birthday/many-many-many-birthdays-2d.png', thumbnail: '/cards/birthday/many-many-many-birthdays.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '40',
      title: 'Mountains',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/mountains.png', back: '/cards/birthday/mountains-2d.png', thumbnail: '/cards/birthday/mountains.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '41',
      title: 'Old Car',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/old-car.png', back: '/cards/birthday/old-car-2d.png', thumbnail: '/cards/birthday/old-car.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '42',
      title: 'Ski Time',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/ski-time.png', back: '/cards/birthday/ski-time-2d.png', thumbnail: '/cards/birthday/ski-time.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '43',
      title: 'Sushi Time',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/sushi-time.png', back: '/cards/birthday/sushi-time-2d.png', thumbnail: '/cards/birthday/sushi-time.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '44',
      title: 'Tacos',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/tacos.png', back: '/cards/birthday/tacos-2d.png', thumbnail: '/cards/birthday/tacos.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '45',
      title: 'Take it easy',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/take-it-easy.png', back: '/cards/birthday/take-it-easy-2d.png', thumbnail: '/cards/birthday/take-it-easy.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '46',
      title: 'To the Gym',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/to-the-gym.png', back: '/cards/birthday/to-the-gym-2d.png', thumbnail: '/cards/birthday/to-the-gym.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '47',
      title: 'Up to par',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/up-to-par.png', back: '/cards/birthday/up-to-par-2d.png', thumbnail: '/cards/birthday/up-to-par.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '48',
      title: 'Yoga',
      description: 'Make their birthday extra special with this vibrant and cheerful card.',
      category: 'birthday',
      price: 4.99,
      images: { front: '/cards/birthday/yoga.png', back: '/cards/birthday/yoga-2d.png', thumbnail: '/cards/birthday/yoga.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Happy Birthday', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    // Congratulations (ID 49)
    {
      id: '49',
      title: 'Congratulations Confetti',
      description: 'Celebrate their achievement with this festive congratulations card.',
      category: 'congratulations',
      price: 4.99,
      images: { front: '/cards/congratulations/congratulations-confetti.png', back: '/cards/congratulations/congratulations-confetti-2d.png', thumbnail: '/cards/congratulations/congratulations-confetti.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Congratulations', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    // For You (IDs 50-51)
    {
      id: '50',
      title: 'Flowers',
      description: 'A thoughtful card to show someone special you care.',
      category: 'for-you',
      price: 4.99,
      images: { front: '/cards/for-you/flowers.png', back: '/cards/for-you/flowers-2d.png', thumbnail: '/cards/for-you/flowers.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'For You', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '51',
      title: 'Tulips with love',
      description: 'A thoughtful card to show someone special you care.',
      category: 'for-you',
      price: 4.99,
      images: { front: '/cards/for-you/tulips-with-love.png', back: '/cards/for-you/tulips-with-love-2d.png', thumbnail: '/cards/for-you/tulips-with-love.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'For You', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    // Get Well Soon (IDs 52-53)
    {
      id: '52',
      title: 'Get well soon heart',
      description: 'Send warm wishes for a speedy recovery with this heartfelt card.',
      category: 'get-well-soon',
      price: 4.99,
      images: { front: '/cards/get-well-soon/get-well-soon-heart.png', back: '/cards/get-well-soon/get-well-soon-heart-2d.png', thumbnail: '/cards/get-well-soon/get-well-soon-heart.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Get Well Soon', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '53',
      title: 'Get well soon well',
      description: 'Send warm wishes for a speedy recovery with this heartfelt card.',
      category: 'get-well-soon',
      price: 4.99,
      images: { front: '/cards/get-well-soon/get-well-soon-well.png', back: '/cards/get-well-soon/get-well-soon-well-2d.png', thumbnail: '/cards/get-well-soon/get-well-soon-well.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Get Well Soon', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    // Good Luck (IDs 54-62)
    {
      id: '54',
      title: 'Adventure Time',
      description: 'Wish them the best of luck on their next adventure.',
      category: 'good-luck',
      price: 4.99,
      images: { front: '/cards/good-luck/adventure-time.png', back: '/cards/good-luck/adventure-time-2d.png', thumbnail: '/cards/good-luck/adventure-time.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Good Luck', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '55',
      title: 'Blocks you got this',
      description: 'Wish them the best of luck on their next adventure.',
      category: 'good-luck',
      price: 4.99,
      images: { front: '/cards/good-luck/blocks-you-got-this.png', back: '/cards/good-luck/blocks-you-got-this-2d.png', thumbnail: '/cards/good-luck/blocks-you-got-this.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Good Luck', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '56',
      title: 'Bon Voyage Suitcase',
      description: 'Wish them the best of luck on their next adventure.',
      category: 'good-luck',
      price: 4.99,
      images: { front: '/cards/good-luck/bon-voyage-suitcase.png', back: '/cards/good-luck/bon-voyage-suitcase-2d.png', thumbnail: '/cards/good-luck/bon-voyage-suitcase.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Good Luck', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '57',
      title: 'Enjoy your trip',
      description: 'Wish them the best of luck on their next adventure.',
      category: 'good-luck',
      price: 4.99,
      images: { front: '/cards/good-luck/enjoy-your-trip.png', back: '/cards/good-luck/enjoy-your-trip-2d.png', thumbnail: '/cards/good-luck/enjoy-your-trip.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Good Luck', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '58',
      title: 'Fingers Crossed',
      description: 'Wish them the best of luck on their next adventure.',
      category: 'good-luck',
      price: 4.99,
      images: { front: '/cards/good-luck/fingers-crossed.png', back: '/cards/good-luck/fingers-crossed-2d.png', thumbnail: '/cards/good-luck/fingers-crossed.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Good Luck', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '59',
      title: 'Lightbulb you got this',
      description: 'Wish them the best of luck on their next adventure.',
      category: 'good-luck',
      price: 4.99,
      images: { front: '/cards/good-luck/lightbulb-you-got-this.png', back: '/cards/good-luck/lightbulb-you-got-this-2d.png', thumbnail: '/cards/good-luck/lightbulb-you-got-this.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Good Luck', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '60',
      title: 'Safe Travels',
      description: 'Wish them the best of luck on their next adventure.',
      category: 'good-luck',
      price: 4.99,
      images: { front: '/cards/good-luck/safe-travels.png', back: '/cards/good-luck/safe-travels-2d.png', thumbnail: '/cards/good-luck/safe-travels.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Good Luck', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '61',
      title: 'Travel icons',
      description: 'Wish them the best of luck on their next adventure.',
      category: 'good-luck',
      price: 4.99,
      images: { front: '/cards/good-luck/travel-icons.png', back: '/cards/good-luck/travel-icons-2d.png', thumbnail: '/cards/good-luck/travel-icons.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Good Luck', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '62',
      title: 'You got this',
      description: 'Wish them the best of luck on their next adventure.',
      category: 'good-luck',
      price: 4.99,
      images: { front: '/cards/good-luck/you-got-this.png', back: '/cards/good-luck/you-got-this-2d.png', thumbnail: '/cards/good-luck/you-got-this.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Good Luck', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    // Misc (ID 63)
    {
      id: '63',
      title: 'Wish you were here',
      description: 'A versatile card for any occasion.',
      category: 'misc',
      price: 4.99,
      images: { front: '/cards/misc/wish-you-were-here.png', back: '/cards/misc/wish-you-were-here-2d.png', thumbnail: '/cards/misc/wish-you-were-here.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Your Message', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    // New Baby (IDs 64-74)
    {
      id: '64',
      title: 'Baby boxes',
      description: 'Welcome the new arrival with this adorable card.',
      category: 'new-baby',
      price: 4.99,
      images: { front: '/cards/new-baby/baby-boxes.png', back: '/cards/new-baby/baby-boxes-2d.png', thumbnail: '/cards/new-baby/baby-boxes.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Welcome Little One', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '65',
      title: 'Enjoy the ride',
      description: 'Welcome the new arrival with this adorable card.',
      category: 'new-baby',
      price: 4.99,
      images: { front: '/cards/new-baby/enjoy-the-ride.png', back: '/cards/new-baby/enjoy-the-ride-2d.png', thumbnail: '/cards/new-baby/enjoy-the-ride.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Welcome Little One', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '66',
      title: "It's a boy",
      description: 'Welcome the new arrival with this adorable card.',
      category: 'new-baby',
      price: 4.99,
      images: { front: '/cards/new-baby/its-a-boy.png', back: '/cards/new-baby/its-a-boy-2d.png', thumbnail: '/cards/new-baby/its-a-boy.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Welcome Little One', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '67',
      title: "It's a boy babygrow",
      description: 'Welcome the new arrival with this adorable card.',
      category: 'new-baby',
      price: 4.99,
      images: { front: '/cards/new-baby/its-a-boy-babygrow.png', back: '/cards/new-baby/its-a-boy-babygrow-2d.png', thumbnail: '/cards/new-baby/its-a-boy-babygrow.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Welcome Little One', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '68',
      title: "It's a girl",
      description: 'Welcome the new arrival with this adorable card.',
      category: 'new-baby',
      price: 4.99,
      images: { front: '/cards/new-baby/its-a-girl.png', back: '/cards/new-baby/its-a-girl-2d.png', thumbnail: '/cards/new-baby/its-a-girl.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Welcome Little One', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '69',
      title: 'Just keep washing',
      description: 'Welcome the new arrival with this adorable card.',
      category: 'new-baby',
      price: 4.99,
      images: { front: '/cards/new-baby/just-keep-washing.png', back: '/cards/new-baby/just-keep-washing-2d.png', thumbnail: '/cards/new-baby/just-keep-washing.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Welcome Little One', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '70',
      title: "Toys It's a boy",
      description: 'Welcome the new arrival with this adorable card.',
      category: 'new-baby',
      price: 4.99,
      images: { front: '/cards/new-baby/toys-its-a-boy.png', back: '/cards/new-baby/toys-its-a-boy-2d.png', thumbnail: '/cards/new-baby/toys-its-a-boy.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Welcome Little One', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '71',
      title: 'Welcome cars',
      description: 'Welcome the new arrival with this adorable card.',
      category: 'new-baby',
      price: 4.99,
      images: { front: '/cards/new-baby/welcome-cars.png', back: '/cards/new-baby/welcome-cars-2d.png', thumbnail: '/cards/new-baby/welcome-cars.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Welcome Little One', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '72',
      title: 'Welcome to the world',
      description: 'Welcome the new arrival with this adorable card.',
      category: 'new-baby',
      price: 4.99,
      images: { front: '/cards/new-baby/welcome-to-the-world.png', back: '/cards/new-baby/welcome-to-the-world-2d.png', thumbnail: '/cards/new-baby/welcome-to-the-world.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Welcome Little One', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '73',
      title: 'Young boy',
      description: 'Welcome the new arrival with this adorable card.',
      category: 'new-baby',
      price: 4.99,
      images: { front: '/cards/new-baby/young-boy.png', back: '/cards/new-baby/young-boy-2d.png', thumbnail: '/cards/new-baby/young-boy.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Welcome Little One', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '74',
      title: 'Your New Home',
      description: 'Welcome the new arrival with this adorable card.',
      category: 'new-baby',
      price: 4.99,
      images: { front: '/cards/new-baby/your-new-home.png', back: '/cards/new-baby/your-new-home-2d.png', thumbnail: '/cards/new-baby/your-new-home.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Welcome Little One', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    // New Home (IDs 75-85)
    {
      id: '75',
      title: 'All the doors',
      description: 'Celebrate their new chapter with this charming new home card.',
      category: 'new-home',
      price: 4.99,
      images: { front: '/cards/new-home/all-the-doors.png', back: '/cards/new-home/all-the-doors-2d.png', thumbnail: '/cards/new-home/all-the-doors.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Welcome Home', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '76',
      title: 'Front Door',
      description: 'Celebrate their new chapter with this charming new home card.',
      category: 'new-home',
      price: 4.99,
      images: { front: '/cards/new-home/front-door.png', back: '/cards/new-home/front-door-2d.png', thumbnail: '/cards/new-home/front-door.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Welcome Home', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '77',
      title: 'Girl on a swing',
      description: 'Celebrate their new chapter with this charming new home card.',
      category: 'new-home',
      price: 4.99,
      images: { front: '/cards/new-home/girl-on-a-swing.png', back: '/cards/new-home/girl-on-a-swing-2d.png', thumbnail: '/cards/new-home/girl-on-a-swing.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Welcome Home', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '78',
      title: 'Kids Drawn Home',
      description: 'Celebrate their new chapter with this charming new home card.',
      category: 'new-home',
      price: 4.99,
      images: { front: '/cards/new-home/kids-drawn-home.png', back: '/cards/new-home/kids-drawn-home-2d.png', thumbnail: '/cards/new-home/kids-drawn-home.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Welcome Home', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '79',
      title: 'Moving van',
      description: 'Celebrate their new chapter with this charming new home card.',
      category: 'new-home',
      price: 4.99,
      images: { front: '/cards/new-home/moving-van.png', back: '/cards/new-home/moving-van-2d.png', thumbnail: '/cards/new-home/moving-van.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Welcome Home', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '80',
      title: 'New Home',
      description: 'Celebrate their new chapter with this charming new home card.',
      category: 'new-home',
      price: 4.99,
      images: { front: '/cards/new-home/new-home.png', back: '/cards/new-home/new-home-2d.png', thumbnail: '/cards/new-home/new-home.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Welcome Home', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '81',
      title: 'New set up',
      description: 'Celebrate their new chapter with this charming new home card.',
      category: 'new-home',
      price: 4.99,
      images: { front: '/cards/new-home/new-set-up.png', back: '/cards/new-home/new-set-up-2d.png', thumbnail: '/cards/new-home/new-set-up.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Welcome Home', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '82',
      title: 'Swirls home sweet home',
      description: 'Celebrate their new chapter with this charming new home card.',
      category: 'new-home',
      price: 4.99,
      images: { front: '/cards/new-home/swirls-home-sweet-home.png', back: '/cards/new-home/swirls-home-sweet-home-2d.png', thumbnail: '/cards/new-home/swirls-home-sweet-home.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Welcome Home', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '83',
      title: 'Unpacking Boxes',
      description: 'Celebrate their new chapter with this charming new home card.',
      category: 'new-home',
      price: 4.99,
      images: { front: '/cards/new-home/unpacking-boxes.png', back: '/cards/new-home/unpacking-boxes-2d.png', thumbnail: '/cards/new-home/unpacking-boxes.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Welcome Home', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '84',
      title: 'Welcome Mats',
      description: 'Celebrate their new chapter with this charming new home card.',
      category: 'new-home',
      price: 4.99,
      images: { front: '/cards/new-home/welcome-mats.png', back: '/cards/new-home/welcome-mats-2d.png', thumbnail: '/cards/new-home/welcome-mats.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Welcome Home', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '85',
      title: 'Welcome sign home Sweet home',
      description: 'Celebrate their new chapter with this charming new home card.',
      category: 'new-home',
      price: 4.99,
      images: { front: '/cards/new-home/welcome-sign-home-sweet-home.png', back: '/cards/new-home/welcome-sign-home-sweet-home-2d.png', thumbnail: '/cards/new-home/welcome-sign-home-sweet-home.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Welcome Home', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    // New Job (IDs 86-89)
    {
      id: '86',
      title: 'Handshake',
      description: 'Congratulate them on their exciting new career move.',
      category: 'new-job',
      price: 4.99,
      images: { front: '/cards/new-job/handshake.png', back: '/cards/new-job/handshake-2d.png', thumbnail: '/cards/new-job/handshake.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Congratulations', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '87',
      title: 'Nailed it',
      description: 'Congratulate them on their exciting new career move.',
      category: 'new-job',
      price: 4.99,
      images: { front: '/cards/new-job/nailed-it.png', back: '/cards/new-job/nailed-it-2d.png', thumbnail: '/cards/new-job/nailed-it.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Congratulations', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '88',
      title: 'You got this',
      description: 'Congratulate them on their exciting new career move.',
      category: 'new-job',
      price: 4.99,
      images: { front: '/cards/new-job/you-got-this.png', back: '/cards/new-job/you-got-this-2d.png', thumbnail: '/cards/new-job/you-got-this.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Congratulations', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '89',
      title: 'You rock',
      description: 'Congratulate them on their exciting new career move.',
      category: 'new-job',
      price: 4.99,
      images: { front: '/cards/new-job/you-rock.png', back: '/cards/new-job/you-rock-2d.png', thumbnail: '/cards/new-job/you-rock.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Congratulations', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    // Thinking of You (ID 90)
    {
      id: '90',
      title: 'Flower delivery',
      description: 'Let them know they are in your thoughts with this lovely card.',
      category: 'thinking-of-you',
      price: 4.99,
      images: { front: '/cards/thinking-of-you/flower-delivery.png', back: '/cards/thinking-of-you/flower-delivery-2d.png', thumbnail: '/cards/thinking-of-you/flower-delivery.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Thinking of You', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    // Wedding (IDs 91-92)
    {
      id: '91',
      title: 'Congratulations Wedding Car',
      description: 'Celebrate the happy couple with this elegant wedding card.',
      category: 'wedding',
      price: 4.99,
      images: { front: '/cards/wedding/congratulations-wedding-car.png', back: '/cards/wedding/congratulations-wedding-car-2d.png', thumbnail: '/cards/wedding/congratulations-wedding-car.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Congratulations', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
    {
      id: '92',
      title: 'Just Married Old Car',
      description: 'Celebrate the happy couple with this elegant wedding card.',
      category: 'wedding',
      price: 4.99,
      images: { front: '/cards/wedding/just-married-old-car.png', back: '/cards/wedding/just-married-old-car-2d.png', thumbnail: '/cards/wedding/just-married-old-car.png' },
      customizable: { frontText: true, backText: false, insideText: true },
      templates: { front: { placeholder: 'Congratulations', maxLength: 50, fontFamily: 'Cormorant Garamond', fontSize: 24, color: '#2C2C2C', position: { x: 400, y: 700 }, alignment: 'center' }, inside: { placeholder: 'Write your heartfelt message here...', maxLength: 200, fontFamily: 'DM Sans', fontSize: 16, color: '#404040', position: { x: 100, y: 300 }, alignment: 'left' } },
    },
  ];

  await prisma.card.createMany({
    data: cardsData,
  });

  console.log(`Seeded ${cardsData.length} cards.`);

  // ─── Users with Addresses ────────────────────────────────────────────
  const passwordHash = await bcrypt.hash('password123', 12);

  const sarah = await prisma.user.create({
    data: {
      id: 'user-1',
      email: 'sarah@example.com',
      firstName: 'Sarah',
      lastName: 'Johnson',
      phone: '555-0123',
      passwordHash,
      createdAt: new Date('2025-12-01'),
      updatedAt: new Date('2026-01-15'),
      addresses: {
        create: {
          id: 'addr-1',
          label: 'Home',
          firstName: 'Sarah',
          lastName: 'Johnson',
          address: '123 Maple Street',
          city: 'London',
          state: '',
          zip: 'SW1A 1AA',
          country: 'GB',
          isDefault: true,
        },
      },
    },
  });

  const john = await prisma.user.create({
    data: {
      id: 'user-2',
      email: 'john@example.com',
      firstName: 'John',
      lastName: 'Smith',
      phone: '',
      passwordHash,
      createdAt: new Date('2026-01-10'),
      updatedAt: new Date('2026-01-20'),
      addresses: {
        create: {
          id: 'addr-2',
          label: 'Home',
          firstName: 'John',
          lastName: 'Smith',
          address: '456 Oak Avenue',
          city: 'Manchester',
          state: '',
          zip: 'M1 1AA',
          country: 'GB',
          isDefault: true,
        },
      },
    },
  });

  console.log(`Seeded ${2} users with addresses.`);

  // ─── Orders with Items ───────────────────────────────────────────────
  // Order 1: Sarah's order with card ID "1" (A Matcha made in heaven)
  await prisma.order.create({
    data: {
      id: 'order-1',
      orderNumber: 'INK-2026-001',
      userId: sarah.id,
      customerEmail: 'sarah@example.com',
      customerFirstName: 'Sarah',
      customerLastName: 'Johnson',
      customerPhone: '555-0123',
      shippingAddress: '123 Maple Street',
      shippingCity: 'London',
      shippingState: '',
      shippingZip: 'SW1A 1AA',
      shippingCountry: 'GB',
      subtotal: 249.50,
      shippingCost: 5.99,
      tax: 0,
      total: 255.49,
      status: 'shipped',
      createdAt: new Date('2026-01-15'),
      updatedAt: new Date('2026-01-18'),
      items: {
        create: {
          id: 'order-item-1',
          cardId: '1',
          customization: {
            frontText: 'Sarah & Michael',
            insideText: 'Wishing you a lifetime of love and happiness together.',
          },
          quantity: 50,
          price: 4.99,
        },
      },
    },
  });

  // Order 2: John's order with card ID "5" (Hearts)
  await prisma.order.create({
    data: {
      id: 'order-2',
      orderNumber: 'INK-2026-002',
      userId: john.id,
      customerEmail: 'john@example.com',
      customerFirstName: 'John',
      customerLastName: 'Smith',
      customerPhone: null,
      shippingAddress: '456 Oak Avenue',
      shippingCity: 'Manchester',
      shippingState: '',
      shippingZip: 'M1 1AA',
      shippingCountry: 'GB',
      videoUrl: '/videos/sample-greeting.mp4',
      videoQrCodeUrl: '/qr-codes/order-2.png',
      subtotal: 4.99,
      shippingCost: 2.99,
      tax: 0,
      total: 7.98,
      status: 'delivered',
      createdAt: new Date('2026-01-20'),
      updatedAt: new Date('2026-01-25'),
      items: {
        create: {
          id: 'order-item-2',
          cardId: '5',
          customization: {
            frontText: 'Happy Birthday Emma!',
            insideText: 'May your special day be filled with joy and laughter.',
          },
          quantity: 1,
          price: 4.99,
        },
      },
    },
  });

  // Order 3: Guest order (no userId) with card ID "15" (All the wheels)
  await prisma.order.create({
    data: {
      id: 'order-3',
      orderNumber: 'INK-2026-003',
      userId: null,
      customerEmail: 'maria@example.com',
      customerFirstName: 'Maria',
      customerLastName: 'Garcia',
      customerPhone: '555-0456',
      shippingAddress: '789 Pine Road',
      shippingCity: 'Edinburgh',
      shippingState: '',
      shippingZip: 'EH1 1AA',
      shippingCountry: 'GB',
      subtotal: 49.90,
      shippingCost: 3.99,
      tax: 0,
      total: 53.89,
      status: 'processing',
      createdAt: new Date('2026-02-01'),
      updatedAt: new Date('2026-02-02'),
      items: {
        create: {
          id: 'order-item-3',
          cardId: '15',
          customization: {
            frontText: 'Thank You',
            insideText: 'Your kindness means the world to us.',
          },
          quantity: 10,
          price: 4.99,
        },
      },
    },
  });

  console.log('Seeded 3 orders with items.');

  // ─── Articles ────────────────────────────────────────────────────────
  await prisma.article.createMany({
    data: [
      {
        slug: 'art-of-the-handwritten-note',
        title: 'The Art of the Handwritten Note',
        excerpt: 'In an age of instant messaging, the handwritten card has become the ultimate luxury. Here is why putting pen to paper still matters.',
        category: 'Stationery',
        date: '2025-12-10',
        readTime: '4 min read',
        image: 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=800&h=500&fit=crop&q=80',
        content: [
          'There is a particular weight to a handwritten card that no digital message can replicate. The texture of the paper beneath your fingertips, the slight imperfections of ink on a page, the knowledge that someone sat down and gave you their undivided attention \u2014 these details carry meaning far beyond the words themselves.',
          'Neuroscience backs this up. Studies from the University of Tokyo have shown that writing by hand activates regions of the brain associated with memory and emotion in ways that typing simply does not. When you write a card, you are not just composing a message \u2014 you are encoding feeling into a physical object.',
          'The resurgence of greeting cards is not nostalgia. It is a deliberate pushback against the ephemeral nature of digital communication. A text disappears into a scroll of notifications. A card sits on a mantelpiece, tucked into a book, or pinned to a board. It occupies space in someone\'s life.',
          'At INKY, we believe the medium is part of the message. Our heavyweight textured stock and luxury finishes are chosen because they elevate the act of giving. When you hand someone an INKY card, they feel the difference before they read a single word.',
          'So the next time you reach for your phone to send a birthday text, consider this: the three minutes it takes to write a card will be remembered longer than any message that vanishes with a swipe.',
        ],
      },
      {
        slug: 'five-cards-you-should-send-this-year',
        title: 'Five Cards You Should Send This Year',
        excerpt: 'Forget the obligatory birthday card. These are the unexpected moments that deserve a proper greeting.',
        category: 'Gifting',
        date: '2025-11-28',
        readTime: '3 min read',
        image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&h=500&fit=crop&q=80',
        content: [
          'We are conditioned to send cards at birthdays and Christmas, and there is nothing wrong with that. But the cards that people remember \u2014 the ones they keep \u2014 are the ones that arrive when least expected.',
          'The "just because" card. No occasion, no reason, just a note that says "I was thinking of you." It is disarmingly simple, and in a world of constant noise, simplicity cuts through.',
          'The "I noticed" card. Your colleague got a promotion. Your neighbour\'s garden looks incredible. Your friend ran their first 5K. These small recognitions, committed to paper, become outsized gestures of kindness.',
          'The "thank you, properly" card. Not a quick text after dinner, but a real, considered thank you sent days later. It says: that evening mattered to me, and I wanted you to know.',
          'The "I\'m sorry" card. Some apologies deserve more than a message. A handwritten card shows vulnerability and intention in a way that a screen never can.',
          'The "welcome" card. New neighbours, new babies, new beginnings. A card marks the moment and says: you are seen, you belong here.',
        ],
      },
      {
        slug: 'colour-psychology-in-greeting-cards',
        title: 'Colour Psychology in Greeting Cards',
        excerpt: 'Why the palette of a card matters as much as the words inside it. A designer\'s guide to choosing the right tone.',
        category: 'Design',
        date: '2025-11-15',
        readTime: '5 min read',
        image: 'https://images.unsplash.com/photo-1502691876148-a84978e59af8?w=800&h=500&fit=crop&q=80',
        content: [
          'Before a single word is read, a greeting card communicates through colour. The palette sets emotional expectations \u2014 warm tones signal intimacy and celebration, cool tones suggest calm and contemplation, and monochrome speaks to sophistication and sincerity.',
          'In card design, restraint is everything. A common mistake is to use too many colours, diluting the emotional signal. The most impactful cards tend to work within a tight palette of two to three colours, using contrast to draw the eye and create hierarchy.',
          'Black and white remains the most powerful combination in greeting card design. It strips away distraction, letting the message and the texture of the paper do the work. There is a reason luxury brands gravitate toward monochrome \u2014 it signals confidence and timelessness.',
          'When introducing colour, consider the occasion. Deep burgundies and forest greens carry the weight appropriate for sympathy or formal celebrations. Soft blushes and warm creams feel right for weddings and new arrivals. Saturated primaries bring energy to birthday and congratulations cards.',
          'At INKY, our design team works within a carefully considered colour system for every card in the collection. Each palette is tested for emotional resonance, print fidelity, and how it interacts with our textured stock. The result is a card that feels intentional from the first glance.',
        ],
      },
      {
        slug: 'how-ai-is-changing-personalisation',
        title: 'How AI Is Changing Personalisation',
        excerpt: 'From generic templates to genuinely unique designs. The technology behind INKY\'s AI card designer.',
        category: 'Technology',
        date: '2025-10-30',
        readTime: '4 min read',
        image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=500&fit=crop&q=80',
        content: [
          'The greeting card industry has operated on the same model for decades: a designer creates a template, a printer produces thousands of identical copies, and customers choose the one that feels closest to what they want to say. It works, but it is inherently impersonal.',
          'Generative AI changes this equation fundamentally. Instead of selecting from a finite catalogue, you describe what you want and the technology creates it. A birthday card for a five-year-old who loves dinosaurs and the colour purple. A wedding card that references the couple\'s shared love of wild swimming. A thank you note in the style of Japanese woodblock prints.',
          'The challenge \u2014 and the reason most AI card tools feel gimmicky \u2014 is quality control. Anyone can generate an image. The hard part is ensuring that image works as a printed card: that the colours translate to CMYK, that the composition leaves space for a message, that the overall aesthetic feels considered rather than chaotic.',
          'INKY\'s AI system is trained with these constraints built in. Every generated design is optimised for our print specifications, our card dimensions, and our quality standards. The result is a card that looks like it was designed by a human, because the AI was taught by humans who understand what makes a great card.',
          'This is not about replacing designers. It is about giving every customer access to bespoke design, regardless of budget or artistic ability. The best cards are personal. AI makes personal possible at scale.',
        ],
      },
      {
        slug: 'seasonal-guide-spring-occasions',
        title: 'The Spring Occasions Guide',
        excerpt: 'From Mother\'s Day to graduation season, a curated guide to the cards you will need this spring.',
        category: 'Seasonal',
        date: '2025-10-12',
        readTime: '3 min read',
        image: 'https://images.unsplash.com/photo-1457530378978-8bac673b8062?w=800&h=500&fit=crop&q=80',
        content: [
          'Spring is the busiest season for greeting cards, and for good reason. The calendar is stacked with occasions that call for something more than a text message.',
          'Mother\'s Day sits at the centre of it all. The cards that resonate most are the ones that avoid clich\u00e9. Skip the generic florals and think about what actually defines your relationship. Is your mother the person who always has the right book recommendation? The one who sends voice notes instead of texts? The card should reflect the specific, not the universal.',
          'Easter and Passover cards have evolved. Where they once leaned heavily on religious imagery, there is a growing appetite for cards that honour the occasion while feeling contemporary. Think clean typography, subtle references to renewal and gathering, and palettes that feel fresh without being frivolous.',
          'Graduation season arrives in late spring, and the best cards here are the ones that resist the urge to be overly sentimental. Graduates want to feel seen as adults stepping into the world, not children being waved off. A sharp, modern design with a sincere message lands harder than a card covered in mortarboards.',
          'The through-line for spring cards is optimism without saccharine. The season itself does the heavy lifting \u2014 your card just needs to match its energy.',
        ],
      },
      {
        slug: 'inside-the-print-studio',
        title: 'Inside the Print Studio',
        excerpt: 'A look at how INKY cards go from screen to paper. The print processes and materials behind the finish.',
        category: 'Craft',
        date: '2025-09-25',
        readTime: '5 min read',
        image: 'https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?w=800&h=500&fit=crop&q=80',
        content: [
          'There is a moment in the print process that never gets old: the first sheet coming off the press, still warm, the ink wet enough to smell. It is the point where a digital file becomes a physical object, and it is where most of the craft lives.',
          'Every INKY card is printed on 350gsm textured stock. The weight matters \u2014 a flimsy card undermines even the most beautiful design. At 350gsm, you feel the card before you see it. The texture adds a tactile dimension that smooth paper simply cannot match.',
          'We use a combination of digital and lithographic printing depending on the design. Digital printing gives us precision and consistency for photographic and gradient-heavy designs. Litho printing, which transfers ink from plate to paper via a rubber blanket, produces richer, more saturated colour for flat and typographic work.',
          'Finishing is where the luxury happens. Select cards in our collection receive spot UV coating \u2014 a clear, glossy layer applied to specific areas of the design that catches the light and creates contrast against the matte stock. Others feature blind embossing, where a die presses a raised pattern into the paper without any ink at all. It is pure texture.',
          'The envelope is not an afterthought. Each INKY card ships with a matched envelope in a complementary tone, chosen to extend the design language of the card itself. First impressions happen at the envelope, and we take that seriously.',
        ],
      },
    ],
  });

  console.log('Seeded 6 articles.');

  console.log('Database seeding complete!');
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
